# Generated by Django 3.0.6 on 2020-05-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
