# Generated by Django 3.0.6 on 2020-05-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
