# Generated by Django 3.0.6 on 2020-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200523_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
