# Generated by Django 3.0.6 on 2020-08-02 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_auto_20200802_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='mescours', to='course.Courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
