# Generated by Django 3.0.6 on 2020-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200802_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='mescours', to='course.Courses'),
        ),
    ]
